import { useEffect, useState, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  RefreshControl,
  ActivityIndicator,
  TouchableOpacity,
  Share,
  Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '@/lib/auth';
import { getDailyReport, getSummaryReport } from '@/lib/api';

const C = {
  bg: '#0b1120',
  card: '#141f35',
  cardBorder: '#1e3356',
  primary: '#5a7fbf',
  hr: '#c75e6b',
  spo2: '#5a9bb5',
  steps: '#5ba88a',
  sleep: '#8b7db8',
  gold: '#bfa45a',
  text: '#e8f0fe',
  textSub: '#7a97c0',
  textMuted: '#3d5478',
};

interface DailyReport {
  date: string;
  heartRate: { avg: number; min: number; max: number; elevatedReadings: number };
  spo2: { avg: number; min: number; lowReadings: number };
  steps: { total: number; activeMinutes: number };
  sleep: { totalMinutes: number; qualityScore: number };
  alertCount: number;
}

interface SummaryReport {
  range: string;
  avgHeartRate: number;
  avgSpo2: number;
  totalSteps: number;
  alertCount: number;
  trendDirection: string;
}

function MetricCard({
  icon, iconColor, iconBg, title, value, unit, subtitle,
}: {
  icon: React.ComponentProps<typeof Ionicons>['name'];
  iconColor: string; iconBg: string; title: string;
  value: string; unit?: string; subtitle?: string;
}) {
  return (
    <View style={[styles.metricCard, { borderColor: iconColor + '30' }]}>
      <View style={[styles.metricIcon, { backgroundColor: iconBg }]}>
        <Ionicons name={icon} size={20} color={iconColor} />
      </View>
      <Text style={styles.metricTitle}>{title}</Text>
      <View style={styles.metricValueRow}>
        <Text style={[styles.metricValue, { color: iconColor }]}>{value}</Text>
        {unit && <Text style={styles.metricUnit}>{unit}</Text>}
      </View>
      {subtitle && <Text style={styles.metricSub}>{subtitle}</Text>}
    </View>
  );
}

export default function ReportsScreen() {
  const { token } = useAuth();
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [daily, setDaily] = useState<DailyReport | null>(null);
  const [summary12h, setSummary12h] = useState<SummaryReport | null>(null);
  const [selectedRange, setSelectedRange] = useState<'12h' | '24h'>('12h');
  const [error, setError] = useState<string | null>(null);

  const fetchReports = useCallback(async () => {
    try {
      setError(null);
      const [d, s] = await Promise.all([
        getDailyReport(token),
        getSummaryReport(token, selectedRange),
      ]);
      setDaily(d);
      setSummary12h(s);
    } catch (e: any) {
      setError(e.message || 'Failed to load reports');
    }
  }, [token, selectedRange]);

  useEffect(() => {
    setLoading(true);
    fetchReports().finally(() => setLoading(false));
  }, [fetchReports]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await fetchReports();
    setRefreshing(false);
  }, [fetchReports]);

  async function handleShareWithDoctor() {
    if (!daily) return;
    const reportText = [
      `VitalWatch Daily Health Report`,
      `Date: ${daily.date}`,
      ``,
      `Heart Rate: Avg ${daily.heartRate.avg} bpm, Min ${daily.heartRate.min}, Max ${daily.heartRate.max}`,
      `Elevated HR readings: ${daily.heartRate.elevatedReadings}`,
      ``,
      `SpO2: Avg ${daily.spo2.avg}%, Min ${daily.spo2.min}%`,
      `Low SpO2 readings (<95%): ${daily.spo2.lowReadings}`,
      ``,
      `Steps: ${daily.steps.total} total, ${daily.steps.activeMinutes} active minutes`,
      ``,
      `Sleep: ${Math.floor(daily.sleep.totalMinutes / 60)}h ${daily.sleep.totalMinutes % 60}m, Quality: ${daily.sleep.qualityScore}/100`,
      ``,
      `Alerts triggered: ${daily.alertCount}`,
      ``,
      `Generated by VitalWatch On-Device AI`,
    ].join('\n');

    try {
      await Share.share({
        message: reportText,
        title: 'VitalWatch Health Report',
      });
    } catch {}
  }

  if (loading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color={C.primary} />
        <Text style={styles.loadingText}>Loading reports...</Text>
      </View>
    );
  }

  const trendIcon: React.ComponentProps<typeof Ionicons>['name'] =
    summary12h?.trendDirection === 'increasing' ? 'trending-up' :
    summary12h?.trendDirection === 'decreasing' ? 'trending-down' : 'remove';
  const trendColor = summary12h?.trendDirection === 'increasing' ? C.hr :
    summary12h?.trendDirection === 'decreasing' ? C.primary : C.steps;

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      refreshControl={
        <RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[C.primary]} tintColor={C.primary} />
      }
    >
      {/* Error Banner */}
      {error && (
        <View style={[styles.summaryCard, { borderColor: C.hr + '40' }]}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            <Ionicons name="warning-outline" size={18} color={C.hr} />
            <Text style={[styles.summaryTitle, { color: C.hr }]}>{error}</Text>
          </View>
        </View>
      )}

      {/* Range Selector */}
      <View style={styles.rangeRow}>
        {(['12h', '24h'] as const).map((r) => (
          <TouchableOpacity
            key={r}
            style={[styles.rangeBtn, selectedRange === r && styles.rangeBtnActive]}
            onPress={() => setSelectedRange(r)}
          >
            <Text style={[styles.rangeBtnText, selectedRange === r && styles.rangeBtnTextActive]}>
              {r === '12h' ? 'Last 12 Hours' : 'Last 24 Hours'}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Quick Summary Card */}
      {summary12h && (
        <View style={styles.summaryCard}>
          <View style={styles.summaryHeader}>
            <Ionicons name="analytics" size={18} color={C.gold} />
            <Text style={styles.summaryTitle}>Quick Summary</Text>
            <View style={styles.trendBadge}>
              <Ionicons name={trendIcon} size={14} color={trendColor} />
              <Text style={[styles.trendText, { color: trendColor }]}>
                {summary12h.trendDirection}
              </Text>
            </View>
          </View>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryValue, { color: C.hr }]}>{summary12h.avgHeartRate}</Text>
              <Text style={styles.summaryLabel}>Avg HR</Text>
            </View>
            <View style={styles.summaryDivider} />
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryValue, { color: C.spo2 }]}>{summary12h.avgSpo2}%</Text>
              <Text style={styles.summaryLabel}>Avg SpO2</Text>
            </View>
            <View style={styles.summaryDivider} />
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryValue, { color: C.steps }]}>{summary12h.totalSteps}</Text>
              <Text style={styles.summaryLabel}>Steps</Text>
            </View>
            <View style={styles.summaryDivider} />
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryValue, { color: summary12h.alertCount > 0 ? C.hr : C.steps }]}>
                {summary12h.alertCount}
              </Text>
              <Text style={styles.summaryLabel}>Alerts</Text>
            </View>
          </View>
        </View>
      )}

      {/* Daily Report */}
      {daily && (
        <>
          <View style={styles.sectionHeader}>
            <Ionicons name="document-text" size={18} color={C.primary} />
            <Text style={styles.sectionTitle}>Daily Health Report</Text>
            <Text style={styles.sectionDate}>{daily.date}</Text>
          </View>

          {/* Metrics Grid */}
          <View style={styles.metricsGrid}>
            <MetricCard
              icon="heart" iconColor={C.hr} iconBg="rgba(255,83,112,0.12)"
              title="Heart Rate" value={String(daily.heartRate.avg)} unit="bpm"
              subtitle={`Min ${daily.heartRate.min} · Max ${daily.heartRate.max}`}
            />
            <MetricCard
              icon="water" iconColor={C.spo2} iconBg="rgba(0,212,255,0.10)"
              title="SpO2" value={`${daily.spo2.avg}`} unit="%"
              subtitle={`Min ${daily.spo2.min}% · ${daily.spo2.lowReadings} low`}
            />
            <MetricCard
              icon="footsteps" iconColor={C.steps} iconBg="rgba(0,229,160,0.10)"
              title="Steps" value={daily.steps.total.toLocaleString()}
              subtitle={`${daily.steps.activeMinutes} active min`}
            />
            <MetricCard
              icon="moon" iconColor={C.sleep} iconBg="rgba(166,127,250,0.12)"
              title="Sleep"
              value={daily.sleep.totalMinutes > 0
                ? `${Math.floor(daily.sleep.totalMinutes / 60)}h ${daily.sleep.totalMinutes % 60}m`
                : 'N/A'}
              subtitle={daily.sleep.qualityScore > 0 ? `Quality: ${daily.sleep.qualityScore}/100` : 'No data'}
            />
            <MetricCard
              icon="pulse" iconColor={C.hr} iconBg="rgba(255,83,112,0.12)"
              title="Elevated HR" value={String(daily.heartRate.elevatedReadings)}
              subtitle="Readings >100 bpm"
            />
            <MetricCard
              icon="notifications" iconColor="#c99a4a" iconBg="rgba(255,176,32,0.12)"
              title="Alerts" value={String(daily.alertCount)}
              subtitle="Triggered today"
            />
          </View>

          {/* Weekly Digest */}
          {daily && (
            <View style={[styles.summaryCard, { borderColor: C.sleep + '30' }]}>
              <View style={styles.summaryHeader}>
                <Ionicons name="calendar-outline" size={18} color={C.sleep} />
                <Text style={styles.summaryTitle}>Weekly Digest</Text>
                <View style={{ backgroundColor: C.sleep + '20', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 }}>
                  <Text style={{ fontSize: 9, fontWeight: '700', color: C.sleep }}>AUTO</Text>
                </View>
              </View>
              <View style={{ gap: 8 }}>
                <View style={styles.digestRow}>
                  <Ionicons name="heart" size={14} color={C.hr} />
                  <Text style={styles.digestLabel}>Avg Heart Rate</Text>
                  <Text style={styles.digestValue}>{daily.heartRate.avg.toFixed(0)} bpm</Text>
                </View>
                <View style={styles.digestRow}>
                  <Ionicons name="water" size={14} color={C.spo2} />
                  <Text style={styles.digestLabel}>Avg SpO2</Text>
                  <Text style={styles.digestValue}>{daily.spo2.avg.toFixed(0)}%</Text>
                </View>
                <View style={styles.digestRow}>
                  <Ionicons name="footsteps" size={14} color={C.steps} />
                  <Text style={styles.digestLabel}>Steps Today</Text>
                  <Text style={styles.digestValue}>{daily.steps.total.toLocaleString()}</Text>
                </View>
                <View style={styles.digestRow}>
                  <Ionicons name="moon" size={14} color={C.sleep} />
                  <Text style={styles.digestLabel}>Sleep</Text>
                  <Text style={styles.digestValue}>
                    {daily.sleep.totalMinutes > 0
                      ? `${Math.floor(daily.sleep.totalMinutes / 60)}h ${daily.sleep.totalMinutes % 60}m`
                      : 'No data'}
                  </Text>
                </View>
                <View style={styles.digestRow}>
                  <Ionicons name="notifications" size={14} color={C.gold} />
                  <Text style={styles.digestLabel}>Alerts</Text>
                  <Text style={[styles.digestValue, daily.alertCount > 0 && { color: C.hr }]}>{daily.alertCount}</Text>
                </View>
              </View>
              <Text style={{ fontSize: 10, color: C.textMuted, marginTop: 10, fontStyle: 'italic' }}>
                Generated {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}
              </Text>
            </View>
          )}

          {/* Share with Doctor */}
          <TouchableOpacity style={styles.shareBtn} onPress={handleShareWithDoctor} activeOpacity={0.8}>
            <Ionicons name="share-outline" size={18} color={C.text} />
            <Text style={styles.shareBtnText}>Share Report with Doctor</Text>
          </TouchableOpacity>
        </>
      )}

      {!daily && !summary12h && (
        <View style={styles.emptyState}>
          <Ionicons name="document-text-outline" size={48} color={C.textMuted} />
          <Text style={styles.emptyTitle}>No report data yet</Text>
          <Text style={styles.emptyHint}>Connect your device and collect some data to generate reports.</Text>
        </View>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  content: { padding: 18, gap: 14, paddingBottom: 40 },
  center: {
    flex: 1, backgroundColor: C.bg, justifyContent: 'center', alignItems: 'center', gap: 12,
  },
  loadingText: { fontSize: 15, color: C.textSub },

  // Range selector
  rangeRow: { flexDirection: 'row', gap: 10 },
  rangeBtn: {
    flex: 1,
    backgroundColor: C.card,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.cardBorder,
  },
  rangeBtnActive: {
    backgroundColor: 'rgba(77,138,240,0.15)',
    borderColor: C.primary + '60',
  },
  rangeBtnText: { fontSize: 13, fontWeight: '600', color: C.textMuted },
  rangeBtnTextActive: { color: C.primary },

  // Summary
  summaryCard: {
    backgroundColor: C.card, borderRadius: 18, padding: 18,
    borderWidth: 1, borderColor: C.cardBorder,
  },
  summaryHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  summaryTitle: { fontSize: 15, fontWeight: '700', color: C.text, flex: 1 },
  trendBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(255,255,255,0.06)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6,
  },
  trendText: { fontSize: 11, fontWeight: '700', textTransform: 'capitalize' },
  summaryGrid: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  summaryItem: { flex: 1, alignItems: 'center', gap: 4 },
  summaryValue: { fontSize: 20, fontWeight: '800' },
  summaryLabel: { fontSize: 10, color: C.textMuted },
  summaryDivider: { width: 1, height: 32, backgroundColor: 'rgba(255,255,255,0.08)' },

  // Section
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: C.text, flex: 1 },
  sectionDate: { fontSize: 12, color: C.textMuted },

  // Metrics grid
  metricsGrid: {
    flexDirection: 'row', flexWrap: 'wrap', gap: 10,
  },
  metricCard: {
    width: '47%' as any,
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    gap: 6,
  },
  metricIcon: {
    width: 36, height: 36, borderRadius: 10,
    justifyContent: 'center', alignItems: 'center',
  },
  metricTitle: { fontSize: 12, color: C.textMuted, fontWeight: '600', marginTop: 4 },
  metricValueRow: { flexDirection: 'row', alignItems: 'baseline', gap: 3 },
  metricValue: { fontSize: 24, fontWeight: '800' },
  metricUnit: { fontSize: 12, color: C.textSub, fontWeight: '600' },
  metricSub: { fontSize: 11, color: C.textMuted },

  // Share
  shareBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    backgroundColor: C.primary, borderRadius: 14, padding: 16,
  },
  shareBtnText: { fontSize: 15, fontWeight: '700', color: C.text },

  // Empty
  emptyState: { alignItems: 'center', paddingTop: 60, gap: 12 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: C.textSub },
  emptyHint: { fontSize: 13, color: C.textMuted, textAlign: 'center', maxWidth: 260, lineHeight: 20 },

  // Digest
  digestRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  digestLabel: { fontSize: 12, color: C.textSub, flex: 1 },
  digestValue: { fontSize: 13, fontWeight: '700', color: C.text },
});
