package com.smartwatch.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Alert - generated by rule engine when thresholds exceeded.
 * e.g. heartRate > 85% of (220 - age).
 */
@Entity
@Table(name = "alerts", indexes = {
    @Index(name = "idx_alerts_timestamp", columnList = "timestamp"),
    @Index(name = "idx_alerts_user_timestamp", columnList = "user_id, timestamp")
})
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String message;

    @Column(nullable = false)
    private LocalDateTime timestamp = LocalDateTime.now();

    @Column(nullable = false)
    private boolean read = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    public enum Severity {
        LOW, MEDIUM, CRITICAL
    }

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private Severity severity = Severity.LOW;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }
    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }
    public boolean isRead() { return read; }
    public void setRead(boolean read) { this.read = read; }
    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }
    public Severity getSeverity() { return severity; }
    public void setSeverity(Severity severity) { this.severity = severity; }
}
