package com.smartwatch.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Vital reading - heartRate, spo2, steps.
 * Generated by scheduler every 5 seconds when device connected.
 * Steps increment cumulatively per user.
 */
@Entity
@Table(name = "vitals", indexes = {
    @Index(name = "idx_vitals_timestamp", columnList = "timestamp"),
    @Index(name = "idx_vitals_user_timestamp", columnList = "user_id, timestamp")
})
public class Vital {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Integer heartRate;
    private Integer spo2;
    private Integer steps;

    @Column(nullable = false)
    private LocalDateTime timestamp = LocalDateTime.now();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Integer getHeartRate() { return heartRate; }
    public void setHeartRate(Integer heartRate) { this.heartRate = heartRate; }
    public Integer getSpo2() { return spo2; }
    public void setSpo2(Integer spo2) { this.spo2 = spo2; }
    public Integer getSteps() { return steps; }
    public void setSteps(Integer steps) { this.steps = steps; }
    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }
    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }
}
